#pragma once

#include "Engine_Function.h"
#include "Engine_Macro.h"
#include "Engine_Typedef.h"
#include "Engine_Struct.h"

using namespace Engine;

extern int g_Pointer;

enum CHANNELID
{
	SOUND_EFFECT,
	SOUND_BGM0, SOUND_BGM0_1, SOUND_BGM1, SOUND_BGM1_1, SOUND_BGM2, SOUND_BGM2_1, SOUND_BGM3, SOUND_BGM3_1, SOUND_OVER,
	SOUND_PLAYER_TALK, SOUND_PLAYER_WALK, SOUND_PLAYER_ATTACK, SOUND_PLAYER_SWING, SOUND_PLAYER_HIT, SOUND_PLAYER_HIT_VOICE, SOUND_GUN1, SOUND_GUN2, SOUND_GUN3, SOUND_GUN4,
	SOUND_RADIO,
	SOUND_ENEMY1, SOUND_ENEMY2, SOUND_ENEMY3,
	SOUND_ENEMY1_VOICE, SOUND_ENEMY2_VOICE, SOUND_ENEMY3_VOICE,
	SOUND_ENEMY1_WALK, SOUND_ENEMY2_WALK, SOUND_ENEMY3_WALK,
	SOUND_ENEMY_HIT, SOUND_ENEMY_BOSS, SOUND_ENEMY_ATTACK,
	SOUND_ENVIRONMENT1, SOUND_ENVIRONMENT2,
	MAXCHANNEL
};